# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleApplication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 4.4’
pod 'ReachabilitySwift', '~> 3'
pod 'ObjectMapper', '~> 3.3'
pod 'SDWebImage', '~>3.8'
pod 'ACTabScrollView', :git => 'https://github.com/azurechen/ACTabScrollView.git'
  # Pods for ExampleApplication

end
